/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3ba008e8-acf1-49dd-81f1-32ee0f5b2b3e",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_NOA818mws",
    "aws_user_pools_web_client_id": "7onc1lch198q81avn7tfmc190m",
    "oauth": {}
};


export default awsmobile;
